
pipeline {
    agent any
    tools {
        maven 'Maven 3.8.6' // Jenkins에서 설정한 Maven 이름
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploying application...'
                // 실제 배포 스크립트 추가
            }
        }
    }
}
